### ISSUE TITLE
only do the "All Settings" thing if the user can actually edit options

### ISSUE THREAD

**Issue by hirasso** [wecodemore/WP-Strip-Naked#4]
If logged in as a user lower than administrator, the variable `$submenu[ 'options-general.php' ]` is `null`. This causes errors in your "admin_menu" function. 

A quick fix for this is to check if the value is an array:

``` php
if( !is_array( $submenu[ 'options-general.php' ] ) )
    return $parent_file;
```

I inserted this block just before this code: 

``` php
// Add all options page instead
add_submenu_page(
    'options-general.php'
    ,__( 'All Options' )
    ,__( 'All Settings' )
    ,'manage_options'
    ,'options.php'
);
```

**Comment by franz-josef-kaiser** [comment]
@hirasso You should have waited until September, 2nd, so we can have an anniversary before closing it :1st_place_medal:

**Comment by hirasso** [comment]
...just doing some cleanup. I never actually used WP-Strip-Naked in production and forgot about it. But then came the GitHub app with it's "open issues created by me" 😰😄
